In [1]:
from sklearn.preprocessing import Normalizer
import numpy as np

# Sample data - replace this with your actual dataset
data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Create a normalizer object
normalizer = Normalizer()

# Fit and transform the data
normalized_data = normalizer.fit_transform(data)

# Display the normalized data
print("Normalized Data:")
print(normalized_data)


Normalized Data:
[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]
 [0.50257071 0.57436653 0.64616234]]
